---

- name: tasks for mysql DB
  ansible.builtin.include_tasks: mysql.yml
  when: db_type == 'mariadb' or db_type == 'mysql'


- name: tasks for postgresql DB
  ansible.builtin.include_tasks: postgresql.yml
  when: db_type == 'postgresql'
